#
#-----------------------------------------------------------------------
#
# This file define a function that, for a specified external model 
# (extrn_mdl_name), sets and returns the default value of the base 
# directory (default_basedir) containing the files generated by that 
# model, if such a directory exists on the machine on which the experiment 
# is generated (and for the experiment mode -- nco or community).  If 
# such a directory does not exist, the function returns a null string 
# for the default base directory.  
#
#-----------------------------------------------------------------------
#
function set_extrn_mdl_default_basedir() {
#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
  { save_shell_opts; set -u +x; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Specify the set of valid argument names for this script/function.  Then
# process the arguments provided to this script/function (which should
# consist of a set of name-value pairs of the form arg1="value1", etc).
#
#-----------------------------------------------------------------------
#
  local valid_args=( \
    "extrn_mdl_name" \
    "outvarname_extrn_mdl_default_basedir" \
    )
  process_args valid_args "$@"
#
#-----------------------------------------------------------------------
#
# For debugging purposes, print out values of arguments passed to this
# script.  Note that these will be printed out only if VERBOSE is set to
# TRUE.
#
#-----------------------------------------------------------------------
#
  print_input_args "valid_args"
#
#-----------------------------------------------------------------------
#
# Declare local variables.
#
#-----------------------------------------------------------------------
#
  local default_basedir
#
#-----------------------------------------------------------------------
#
# Set the default value of the base directory (default_basedir) in which 
# the files generated by the external model specified by extrn_mdl_name 
# are located.  The way this is set depends on the experiment mode (NCO 
# or community), the machine on which the experiment is being generated, 
# and the external model.
#
# Note that default_basedir may be unspecified for certain combinations 
# of experiment mode, machine, and external model.  In such casea, it 
# will remain set to its initial value of a null string.
#
#-----------------------------------------------------------------------
#
  default_basedir=""

  if [ "${RUN_ENVIR}" = "nco" ]; then

    default_basedir="$COMINgfs"

  else

    case "$MACHINE" in

    "WCOSS_CRAY")
      case "${extrn_mdl_name}" in
      "FV3GFS")
        default_basedir="/gpfs/dell1/nco/ops/com/gfs/prod"
        ;;
      "RAP")
        default_basedir="/gpfs/hps/nco/ops/com/rap/prod"
        ;;
      "HRRR")
        default_basedir="/gpfs/hps/nco/ops/com/hrrr/prod"
        ;;
      "NAM")
        default_basedir="/gpfs/dell1/nco/ops/com/nam/prod"
        ;;
      esac
      ;;

    "WCOSS_DELL_P3")
      case "${extrn_mdl_name}" in
      "FV3GFS")
        default_basedir="/gpfs/dell1/nco/ops/com/gfs/prod"
        ;;
      "RAP")
        default_basedir="/gpfs/hps/nco/ops/com/rap/prod"
        ;;
      "HRRR")
        default_basedir="/gpfs/hps/nco/ops/com/hrrr/prod"
        ;;
      "NAM")
        default_basedir="/gpfs/dell1/nco/ops/com/nam/prod"
        ;;
      esac
      ;;

    "HERA")
      case "${extrn_mdl_name}" in
      "FV3GFS")
        default_basedir="/scratch1/NCEPDEV/rstprod/com/gfs/prod"
        ;;
      "RAP")
        default_basedir="/scratch2/BMC/public/data/gsd/rap/full/wrfnat"
        ;;
      "HRRR")
        default_basedir="/scratch2/BMC/public/data/gsd/hrrr/conus/wrfnat"
        ;;
      esac
      ;;

    "JET")
      case "${extrn_mdl_name}" in
      "FV3GFS")
        default_basedir="/public/data/grids/gfs/nemsio"
        ;;
      "RAP")
        default_basedir="/misc/whome/rtrr/rap"
        ;;
      "HRRR")
        default_basedir="/misc/whome/rtrr/hrrr"
        ;;
      esac
      ;;

    "ODIN")
      case "${extrn_mdl_name}" in
      "GSMGFS")
        default_basedir="/scratch/ywang/EPIC/GDAS/2019053000_mem001"
        ;;
      "FV3GFS")
        default_basedir="/scratch/ywang/test_runs/FV3_regional/gfs"
        ;;
      esac
      ;;

    "STAMPEDE")
      case "${extrn_mdl_name}" in
      "GSMGFS")
        default_basedir="/scratch/00315/tg455890/GDAS/20190530/2019053000_mem001"
        ;;
      "FV3GFS")
        default_basedir="/scratch/00315/tg455890/GDAS/20190530/2019053000_mem001"
        ;;
      esac
      ;;

    "CHEYENNE")
      case "${extrn_mdl_name}" in
      "GSMGFS")
        default_basedir="/glade/p/ral/jntp/UFS_CAM/COMGFS"
        ;;
      "FV3GFS")
        default_basedir="/glade/p/ral/jntp/UFS_CAM/COMGFS"
        ;;
      esac
      ;;

    esac

  fi
#
#-----------------------------------------------------------------------
#
# If default_basedir was not set above to a non-empty string, the returned 
# value (in the variable specified by outvarname_extrn_mdl_default_basedir) 
# will be a null string.  In this case, print out an informational message.
#
#-----------------------------------------------------------------------
#
  if [ -z "${default_basedir}" ]; then
    print_info_msg "
A default value for the base directory (default_basedir) is 
not specified for this combination of experiment mode (RUN_ENVIR), machine 
(MACHINE), and external model (extrn_mdl_name):
  RUN_ENVIR = \"${RUN_ENVIR}\"
  MACHINE = \"${MACHINE}\"
  extrn_mdl_name = \"${extrn_mdl_name}\"
  default_basedir = \"${default_basedir}\"
Setting the output variable \"${outvarname_extrn_mdl_default_basedir}\" to a null string.
"
  fi
#
#-----------------------------------------------------------------------
#
# Use the eval function to set the output variables.  Note that each of
# these is set only if the corresponding input variable specifying the
# name to use for the output variable is not empty.
#
#-----------------------------------------------------------------------
#
  if [ ! -z "${outvarname_extrn_mdl_default_basedir}" ]; then
    eval ${outvarname_extrn_mdl_default_basedir}="${default_basedir}"
  fi
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/function.
#
#-----------------------------------------------------------------------
#
  { restore_shell_opts; } > /dev/null 2>&1

}
