#
# TEST PURPOSE/DESCRIPTION:
# ------------------------
#
# This test checks the capability of the workflow to retrieve from a
# user-specified location on disk (as opposed to a default location)
# grib2-formatted output files generated by the FV3GFS external model
# (from which ICs and LBCs will be derived) using the external model's
# default output directory structure and file naming convention.
#
# Note that in this test, we explicitly set EXTRN_MDL_DIR_FILE_LAYOUT
# to its default value of "native_to_extrn_mdl".  This is in principle
# redundant, but the WE2E testing script checks whether or not this
# parameter is set in this file to determine whether or not it needs to
# set the base directories for ICs and LBCs to user-specified values.
# If so, it sets the base directories (EXTRN_MDL_BASEDIR_ICS and
# EXTRN_MDL_BASEDIR_LBCS) explicitly to user-specified values in the
# experiment configuration file that it generates for this test.  If
# not, it leaves the base directories unset (so that they get set to the
# default locations during the experiment generation step).  Thus, since
# we are specifying EXTRN_MDL_DIR_FILE_LAYOUT here, EXTRN_MDL_BASEDIR_ICS
# and EXTRN_MDL_BASEDIR_LBCS will also be explicitly set in the experiment
# configuration file.
#

RUN_ENVIR="community"
PREEXISTING_DIR_METHOD="rename"

PREDEF_GRID_NAME="RRFS_CONUS_25km"
CCPP_PHYS_SUITE="FV3_GFS_v15p2"

EXTRN_MDL_NAME_ICS="FV3GFS"
FV3GFS_FILE_FMT_ICS="grib2"
EXTRN_MDL_NAME_LBCS="FV3GFS"
FV3GFS_FILE_FMT_LBCS="grib2"

EXTRN_MDL_DATA_SOURCES=( "disk" )
EXTRN_MDL_DIR_FILE_LAYOUT="native_to_extrn_mdl"

DATE_FIRST_CYCL="20210603"
DATE_LAST_CYCL="20210603"
CYCL_HRS=( "06" )

FCST_LEN_HRS="6"
LBC_SPEC_INTVL_HRS="3"
