#
# TEST PURPOSE/DESCRIPTION:
# ------------------------
#
# This test checks the capability of the workflow to retrieve from a 
# user-specified location on disk (as opposed to a default location) 
# grib2-formatted output files generated by the FV3GFS external model 
# (from which ICs and LBCs will be derived) using a user-specified 
# format for the external model's output directory structure and file 
# naming convention (i.e. with EXTRN_MDL_DIR_FILE_LAYOUT set to 
# "user_spec", as opposed to the default value of "extrn_mdl").
#

RUN_ENVIR="community"
PREEXISTING_DIR_METHOD="rename"

PREDEF_GRID_NAME="RRFS_CONUS_25km"
CCPP_PHYS_SUITE="FV3_GFS_v15p2"

EXTRN_MDL_NAME_ICS="FV3GFS"
FV3GFS_FILE_FMT_ICS="grib2"
EXTRN_MDL_NAME_LBCS="FV3GFS"
FV3GFS_FILE_FMT_LBCS="grib2"

EXTRN_MDL_DATA_SOURCES=( "disk" )
EXTRN_MDL_DIR_FILE_LAYOUT="user_spec"

DATE_FIRST_CYCL="20210603"
DATE_LAST_CYCL="20210603"
CYCL_HRS=( "06" )

FCST_LEN_HRS="6"
LBC_SPEC_INTVL_HRS="3"
