#
# TEST PURPOSE/DESCRIPTION:
# ------------------------
#
# This test checks the capability of the workflow to retrieve from the
# default location on disk netcdf-formatted output files generated by the 
# FV3GFS external model (from which ICs and LBCs will be derived) using
# the external model's default format for its output directory structure 
# and file naming convention (i.e. with EXTRN_MDL_FILE_NAMING_CONVENTION 
# left unspecified so that it takes on its default value of "extrn_mdl").
#
# Note that the default locations on disk are system directories that
# usually contain only the most recent few days' files (e.g. the last 
# two days).  For this reason, the starting day of the forecast is set 
# here to be "1 days ago" (i.e. yesterday).
#

RUN_ENVIR="community"
PREEXISTING_DIR_METHOD="rename"

PREDEF_GRID_NAME="RRFS_CONUS_25km"
CCPP_PHYS_SUITE="FV3_GFS_v15p2"

EXTRN_MDL_NAME_ICS="FV3GFS"
FV3GFS_FILE_FMT_ICS="netcdf"
EXTRN_MDL_NAME_LBCS="FV3GFS"
FV3GFS_FILE_FMT_LBCS="netcdf"

DATE_FIRST_CYCL=$( date --utc --date="1 days ago" "+%Y%m%d" )
DATE_LAST_CYCL="${DATE_FIRST_CYCL}"
CYCL_HRS=( "06" )

FCST_LEN_HRS="6"
LBC_SPEC_INTVL_HRS="3"

EXTRN_MDL_DATA_SOURCES=( "disk" )
