#
# TEST PURPOSE/DESCRIPTION:
# ------------------------
#
# This test checks the capability of the workflow to retrieve from a 
# system directory grib2-formatted output files generated by the FV3GFS 
# external model (from which ICs and LBCs will be derived).
#
# Note that if the user doesn't specify the system directory in the 
# experiment configuration file, the experiment generation scripts will
# set them to default values.  Since the default system directories 
# usually contain only the most recent few days' files (e.g. the last 
# two days), the files needed to run this test are in fact stored in a
# non-system directory, and that directory is specified in the WE2E test
# launch script.  However, the file naming convention used in this non-
# system directory is the same as the one used in the system directory.
#

RUN_ENVIR="community"
PREEXISTING_DIR_METHOD="rename"

PREDEF_GRID_NAME="RRFS_CONUS_25km"
CCPP_PHYS_SUITE="FV3_GFS_v15p2"

EXTRN_MDL_NAME_ICS="FV3GFS"
FV3GFS_FILE_FMT_ICS="grib2"
EXTRN_MDL_NAME_LBCS="FV3GFS"
FV3GFS_FILE_FMT_LBCS="grib2"

DATE_FIRST_CYCL="20210603"
DATE_LAST_CYCL="20210603"
CYCL_HRS=( "06" )

FCST_LEN_HRS="6"
LBC_SPEC_INTVL_HRS="3"

EXTRN_MDL_DATA_SOURCES=( "sys_dir" )
