#
# TEST PURPOSE/DESCRIPTION:
# ------------------------
#
# This test checks the capability of the workflow to retrieve from NOMADS 
# (NOAA Operational Model Archive and Distribution System) grib2-formatted 
# output files generated by the FV3GFS external model (from which ICs and 
# LBCs will be derived).
#
# Note that NOMADS hosts only the most recent few days' files.  For this 
# reason, the first cycle day of the experiment is set here to be "2 days 
# ago" and the last cycle day is set to "1 days ago" (i.e. yesterday).  
# We use two cycle days to test the capability of the scripts to fetch 
# files from NOMADS for multiple cycles. 
#

RUN_ENVIR="community"
PREEXISTING_DIR_METHOD="rename"

PREDEF_GRID_NAME="RRFS_CONUS_25km"
CCPP_PHYS_SUITE="FV3_GFS_v15p2"

EXTRN_MDL_NAME_ICS="FV3GFS"
FV3GFS_FILE_FMT_ICS="grib2"
EXTRN_MDL_NAME_LBCS="FV3GFS"
FV3GFS_FILE_FMT_LBCS="grib2"

EXTRN_MDL_DATA_SOURCES=( "nomads" )

DATE_FIRST_CYCL=$( date --utc --date="2 days ago" "+%Y%m%d" )
DATE_LAST_CYCL=$( date --utc --date="1 days ago" "+%Y%m%d" )
CYCL_HRS=( "00" )

FCST_LEN_HRS="6"
LBC_SPEC_INTVL_HRS="3"
