#!/bin/ksh
 
set -x

# HOMEdir set in qsub job

. $HOMEdir/jobs/JFV3SAR_ENVIR

. /usrx/local/prod/lmod/lmod/init/ksh
module purge
module use ${HOMEgfs}/sorc/fv3gfs.fd/modulefiles/wcoss_dell_p3
module load fv3
module load prod_util/1.1.0
module list

##############################################
# Specify Execution Areas
##############################################
export NDATE=/gpfs/dell1/nco/ops/nwprod/prod_util.v1.1.0/exec/ips/ndate
export WGRIB2=/gpfs/dell2/emc/modeling/noscrub/${USER}/fv3reg_da_hourly/exec/wgrib2new

export EXECfv3=${HOMEgfs}/exec

##############################################
# Working directories
##############################################
mkdir -p /gpfs/${delldir}/${tmpdir}/${LOGNAME}/tmpnwprd_hourly/${jobname}
export DATA=/gpfs/${delldir}/${tmpdir}/${LOGNAME}/tmpnwprd_hourly/${jobname}
cd /gpfs/${delldir}/${tmpdir}/${LOGNAME}/tmpnwprd_hourly/${jobname}

export FCSTDIR=/gpfs/${delldir}/${tmpdir}/${LOGNAME}/tmpnwprd_hourly/forecast.tm00_${cyc}

##############################################
# Obtain unique process id (pid) and determine job output name on system
##############################################
export pid=$$
export pgmout="OUTPUT.${pid}"

##############################################
# Initialize PDY variables
##############################################
# Get my date file; cyc is tm00 date, comes from qsub script
cp $DATEdir/t${cyc}z ncepdate

###cp /com/date/t${cyc}z ncepdate
export CYCLE=`cut -c 7-16 ncepdate`
export PDY=`cut -c 7-14 ncepdate`

# fhr and cyc set in jobname in LSF script

##############################################
# Define COM directories
##############################################
#COMROOT and GESROOT are the same dirs
mkdir -p $COMROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}
export COMOUT=$COMROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $GESROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}
export NWGES=$GESROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}

##############################################
# Execute the script.
##############################################
${SCRIPTdir}/exfv3sar_post.sh

cat err 
cat $pgmout

###if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $FCSTDIR ; fi
if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $DATA ; fi

date

exit
