#!/bin/ksh
 
set -x

# HOMEdir set in qsub job

. $HOMEdir/jobs/JFV3SAR_ENVIR

# fhr and cyc set in jobname in LSF script

##############################################
# Working directories
##############################################
mkdir -p /gpfs/${delldir}/${tmpdir}/${LOGNAME}/tmpnwprd_hourly
export DATA=/gpfs/${delldir}/${tmpdir}/${LOGNAME}/tmpnwprd_hourly
cd /gpfs/${delldir}/${tmpdir}/${LOGNAME}/tmpnwprd_hourly/

export FCSTDIR=/gpfs/${delldir}/${tmpdir}/${LOGNAME}/tmpnwprd_hourly/forecast.tm00_${cyc}
export POSTMGR=/gpfs/${delldir}/${tmpdir}/${LOGNAME}/tmpnwprd_hourly/post_manager_tm00_${cyc}

##############################################
# Obtain unique process id (pid) and determine job output name on system
##############################################
export pid=$$
export pgmout="OUTPUT.${pid}"

##############################################
# Initialize PDY variables
##############################################
# Get my date file; cyc is tm00 date, comes from qsub script
cp $DATEdir/t${cyc}z ncepdate

###cp /com/date/t${cyc}z ncepdate
export CYCLE=`cut -c 7-16 ncepdate`
export PDY=`cut -c 7-14 ncepdate`

fhr=00
endfhr=$NHRS

typeset -Z2 fhr

while [ $fhr -le $endfhr ]
do
   if [ -s $FCSTDIR/postdone${fhr}.tm00 ]
   then
     echo "found $fhr"
   else
     echo "NOT ALL THE DONE FILES EXIST IN $DATA.  WILL NOT REMOVE THE FCST TMP DIR!"
     exit 10
   fi
   let "fhr=fhr+1"
done

cd $DATA
if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $FCSTDIR ; fi
if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $POSTMGR ; fi

date

exit
