#!/bin/ksh
 
set -x

# HOMEdir set in qsub job

. $HOMEdir/jobs/JFV3SAR_ENVIR

export machine=DELL
export NDATE=/gpfs/dell1/nco/ops/nwprod/prod_util.v1.1.0/exec/ips/ndate
export NHOUR=/gpfs/dell1/nco/ops/nwprod/prod_util.v1.1.0/exec/ips/nhour

. /usrx/local/prod/lmod/lmod/init/ksh
module load prod_util/1.1.0

##############################################
# Initialize PDY variables
##############################################
# Get my date file; cyc is tm00 date, comes from qsub script
cp $DATEdir/t${cyc}z ncepdate

###cp /com/date/t${cyc}z ncepdate
export CYCLE=`cut -c 7-16 ncepdate`
export PDY=`cut -c 7-14 ncepdate`
export CYCLEtm12=`$NDATE -12 $CYCLE`
export CYCLEtm06=`$NDATE -06 $CYCLE`
export PDYtm06=`echo $CYCLEtm06 | cut -c 1-8`
export cyctm06=`echo $CYCLEtm06 | cut -c 9-10`

export vlddate=$CYCLEtm06
export SDATE=$CYCLEtm06
export cyc=`echo $CYCLEtm06 | cut -c 9-10`
export cya=`echo $CYCLEtm06 | cut -c 9-10`
export CYC=`echo $CYCLEtm06 | cut -c 9-10`
export PDY=`echo $CYCLEtm06 | cut -c 1-8`
export PDYrun=`echo $CYCLE | cut -c 1-8`
export PDYa=`echo $CYCLEtm06 | cut -c 1-8`
export CYCrun=`echo $CYCLE | cut -c 9-10`

##############################################
# Obtain unique process id (pid) and make temp directory
##############################################
export DATA=/gpfs/${delldir}/${tmpdir}/${LOGNAME}/tmpnwprd_hourly/${jobname}_${cyc}
mkdir -p $DATA
cd $DATA

export pid=$$
export pgmout="OUTPUT.${pid}"

##############################################
# Define COM directories
##############################################
#COMROOT and GESROOT are the same dirs
mkdir -p $COMROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}
export COMOUT=$COMROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}
export COMOUTtm06=$COMROOT/${RUN}/${envir}/${RUN}.${PDYtm06}/${cyctm06}
mkdir -p $GESROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}
export NWGES=$GESROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}

mkdir -p $COMOUT/guess.${tmmark}
mkdir -p $COMOUT/anl.${tmmark}
export GUESSdir=$COMOUT/guess.${tmmark}
export ANLdir=$COMOUT/anl.${tmmark}

##############################################
# Specify Execution Areas
##############################################
# Set path/file for gsi executable

if [ $machine = THEIA ] ; then
  export UTIL=/scratch4/NCEPDEV/meso/save/${USER}/run_it_regional/exec
  export gsiexec=/scratch4/NCEPDEV/meso/noscrub/Wanshu.Wu/build/bin/gsi.x
  export fixgsi=/scratch4/NCEPDEV/meso/save/Wanshu.Wu/Code/ProdGSI/fix
  export fixcrtm=/scratch4/NCEPDEV/da/save/Michael.Lueken/nwprod/lib/crtm/2.2.3/fix_update
fi
if [ $machine = WCOSS ] ; then
  export UTIL=$HOMEdir/util/ush
  export gsiexec=/meso/save/${USER}/fv3reg_aug2018/fv3gsi_reg/build/bin/gsi.x
  export fixgsi=/meso/save/${USER}/fv3reg_aug2018/fv3gsi_reg/ProdGSI/fix
  export fixcrtm=/da/save/Michael.Lueken/CRTM_REL-2.2.3/crtm_v2.2.3/fix_update
fi
if [ $machine = DELL ] ; then
  export UTIL=$HOMEdir/util/ush
  export gsiexec=${HOMEgfs}/sorc/gsi.fd/build/bin/gsi.x
  export fixgsi=${HOMEgfs}/sorc/gsi.fd/fix
  export fixcrtm=/gpfs/dell1/nco/ops/nwprod/lib/crtm/v2.2.6/fix
fi

# setup ensemble filelist03

if [ $machine = THEIA ] ; then
   COMINgfs=/scratch4/NCEPDEV/rstprod/com/gfs/prod
   COMINnam=/scratch4/NCEPDEV/rstprod/com/nam/prod
   COMINrtma=/scratch4/NCEPDEV/rstprod/com/rtma2p5/prod
   # bias correction files from prev cycle
   COMINbias=$COMOUTtm06
fi
if [ $machine = WCOSS_C -o $machine = WCOSS -o $machine = DELL ] ; then
   COMINgfs=/gpfs/hps/nco/ops/com/gfs/prod
   # This is the FV3GDAS enkf I mirror to dev
   COMINgfspll=/gpfs/gp2/ptmp/${USER}/prfv3rt1
   COMINnam=/gpfs/gp2/nco/ops/com/nam/prod
   COMINrap=/gpfs/hps/nco/ops/com/rap/prod
   COMINbias=$COMOUTtm06
   COMINrtma=/gpfs/gp2/nco/ops/com/rtma/prod
   MYGDASpll=$COMINgfspll/gdas.${PDYa}/${cya}
   GBGDASpll=/gpfs/dell3/ptmp/emc.glopara/ROTDIRS/prfv3rt1/gdas.${PDYa}/${cya}
fi

##############################################
# Execute the script.
##############################################
${SCRIPTdir}/exfv3sar_gsianl_firstguess.sh

cat $pgmout
cat stderr

if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $DATA ; fi

date

exit
