#!/bin/ksh
set -u -x

. $HOMEfv3/jobs/JFV3CAM_SAR_ENVIR
#
#-----------------------------------------------------------------------
#
# Source function definition files.
#
#-----------------------------------------------------------------------
#
. $USHfv3/source_funcs.sh
#
#-----------------------------------------------------------------------
#
# Create the work(??) directory for the surface climatology files.  If   <<-- Should call this "work" directory, since there is a subdirectory that's the true work directory.  Should rename WORKDIR_SFC_CLIMO (and also WORKDIR_GRID, WORKDIR_SHVE, etc).
# it already exists, deal with it as specified by the variable pre-
# existing_dir_method.
#
#-----------------------------------------------------------------------
#
WORKDIR_SFC_CLIMO=${COMROOT}/sfc_climo
check_for_preexist_dir ${WORKDIR_SFC_CLIMO} ${preexisting_dir_method}
mkdir_vrfy -p "${WORKDIR_SFC_CLIMO}"
#
#-----------------------------------------------------------------------
#
# Create a (true) work directory.  If it already exists, delete it.
#
#-----------------------------------------------------------------------
#
WORKDIR_LOCAL="${WORKDIR_SFC_CLIMO}/tmp"
check_for_preexist_dir ${WORKDIR_LOCAL} "delete"
mkdir_vrfy ${WORKDIR_LOCAL}
#
#-----------------------------------------------------------------------
#
# Change location to the temporary directory.
#
#-----------------------------------------------------------------------
#
cd_vrfy ${WORKDIR_LOCAL}
#
#-----------------------------------------------------------------------
#
# Set the tile number(s).  The stand-alone regional and global nest are 
# assumed to be tile 7.
#
#-----------------------------------------------------------------------
#
if [[ "$gtype" == "regional" ]]; then
  tiles=("7")
elif [[ "$gtype" == "nest" ]]; then
  tiles=("1" "2" "3" "4" "5" "6" "7")
else
  tiles=("1" "2" "3" "4" "5" "6")
fi

prefix="\"${CRES}_oro_data.tile"
#prefix="\"${CRES}.oro_data.tile"
orog_fns=( "${tiles[@]/#/$prefix}" )
suffix=".nc\""
orog_fns=( "${orog_fns[@]/%/$suffix}" )
#
#-----------------------------------------------------------------------
#
# Create the namelist that the sfc_climo_gen code will read in.
#
# Question: Should this instead be created from a template file?
#
#-----------------------------------------------------------------------
#
mosaic_file="${WORKDIR_GRID}/${CRES}_mosaic.nc"

cat << EOF > ./fort.41
&config
input_facsf_file="${SFC_CLIMO_INPUT_DIR}/facsf.1.0.nc"
input_substrate_temperature_file="${SFC_CLIMO_INPUT_DIR}/substrate_temperature.2.6x1.5.nc"
input_maximum_snow_albedo_file="${SFC_CLIMO_INPUT_DIR}/maximum_snow_albedo.0.05.nc"
input_snowfree_albedo_file="${SFC_CLIMO_INPUT_DIR}/snowfree_albedo.4comp.0.05.nc"
input_slope_type_file="${SFC_CLIMO_INPUT_DIR}/slope_type.1.0.nc"
input_soil_type_file="${SFC_CLIMO_INPUT_DIR}/soil_type.statsgo.0.05.nc"
input_vegetation_type_file="${SFC_CLIMO_INPUT_DIR}/vegetation_type.igbp.0.05.nc"
input_vegetation_greenness_file="${SFC_CLIMO_INPUT_DIR}/vegetation_greenness.0.144.nc"
mosaic_file_mdl="${mosaic_file}"
orog_dir_mdl="${WORKDIR_SHVE}"
orog_files_mdl=${orog_fns}
halo=${nh4_T7}
maximum_snow_albedo_method="bilinear"
snowfree_albedo_method="bilinear"
vegetation_greenness_method="bilinear"
/
EOF

#
#-----------------------------------------------------------------------
#
# Print message indicating successful completion of script.
#
#-----------------------------------------------------------------------
#
print_info_msg "\

========================================================================
All surface climatology files generated successfully!!!
========================================================================"


exit




. $HOMEfv3/jobs/JFV3CAM_SAR_ENVIR

####################################
# Specify Execution Areas
####################################
export CHGRESEXEC=$EXECfv3/global_chgres
export CHGRESSH=$USHfv3/global_chgres.sh
export GETGES=$HOMEfv3/util/ush/getges_linkges_hourlypgrb_new.sh

####################################
# Run setpdy and initialize PDY variables
####################################
# PDY, CDATE, and tmmark are passed in through Rocoto xml
#setpdy.sh
#. ./PDY

export CYCLEguess=`$NDATE -12 $CDATE`
export ymd=`echo $CDATE | cut -c 1-8`
export hhcyc=`echo $CDATE | cut -c 9-10`

#####################################
# Working directories
#####################################
export DATA=${DATA:-${mainroot}/${tmpdir}/${USER}/tmpnwprd/${job}_${cyc}}
mkdir -p $DATA
cd $DATA

export OUTDIR=$DATA/INPUT
mkdir -p $OUTDIR

export pid=$$
export pgmout="OUTPUT.${pid}"

#####################################
# Define COM directories
#####################################
export COMINgdas=${COMINgdas:-/gpfs/dell1/nco/ops/com/gfs/prod}
export GBCOMINgfs=${GBCOMINgfs:-/gpfs/dell1/nco/ops/com/gfs/prod}
export COMINgfs=${COMINgfs:-/gpfs/dell1/nco/ops/com/gfs/prod}
export COMgfs=${COMgfs:-/gpfs/dell1/nco/ops/com/gfs/prod}
export INIDIR=${COMgfs}/gfs.$PDY/$cyc

export COMOUT=${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $COMOUT
export NWGES=${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $NWGES

if [ $tmmark = tm12 ] ; then	# SAR-DA
  export INPdir=$COMOUT/gfsanl.$tmmark
elif [ $tmmark = tm00 ] ; then	# SAR without DA
  export INPdir=$COMOUT/anl.${dom}.$tmmark
fi
mkdir -p $INPdir

#####################################
# WCOSS environment settings
#####################################
export CDUMP=gfs
export CDAS=gfs
export LEVS=65
export LSOIL=4
export REGIONAL=1		# REGIONAL=0 - uniform, stretch, or nest
				# REGIONAL=1 - generate data and boundary (for regional case)
				# REGIONAL=2 - generate boundaries only (for regional case)
export HALO=4
export ictype=pfv3gfs
export nst_anl=.false.		# false or true to include NST analysis
export KMP_AFFINITY=disabled
export NTRAC=7			# output all gfdl mp tracers

env

#####################################
# Generate the ICs and BC hour 0
#####################################
#
# set the links to use the 4 halo grid and orog files
# these are necessary for creating the boundary data
#
ln -sf $FIXsar/${CASE}_grid.tile7.halo4.nc $FIXsar/${CASE}_grid.tile7.nc
ln -sf $FIXsar/${CASE}_oro_data.tile7.halo4.nc $FIXsar/${CASE}_oro_data.tile7.nc

#####################################
# Execute the script.
${HOMEfv3}/scripts/exfv3cam_sar_chgres.sh
export err=$?
#####################################

mv $OUTDIR/gfs*nc $INPdir/.
mv $OUTDIR/sfc*nc $INPdir/.

#####################################
# Generate BCs for NHRSguess for SAR-DA
#####################################
if [ $tmmark = tm12 ] ; then
  export REGIONAL=2

# NHRSguess comes from JFV3CAM_SAR_ENVIR
  hour=3
  end_hour=$NHRSguess
  while (test "$hour" -le "$end_hour")
  do
    if [ $hour -lt 10 ] ; then
      hour_name='00'$hour
    elif [ $hour -lt 100 ] ; then
      hour_name='0'$hour
    else
      hour_name=$hour
    fi

    export bchour=$hour_name
    ${HOMEfv3}/scripts/exfv3cam_sar_chgres.sh

    mv $OUTDIR/gfs_bndy.tile7.${bchour}.nc $INPdir/.

    err=$?
    if [ $err -ne 0 ] ; then
      echo "bndy file not created, abort"
      exit 10
    fi
    hour=`expr $hour + 3`
  done
fi

cat err
cat $pgmout

exit $err
