#!/bin/ksh
 
set -x

# HOMEdir set in qsub job

. $HOMEdir/jobs/JFV3SAR_ENVIR

. /usrx/local/prod/lmod/lmod/init/ksh
module load prod_util/1.1.0
module load HPSS/5.0.2.5

##############################################
# Initialize PDY variables
##############################################
cp $DATEdir/t${cyc}z ncepdate
export CYCLE=`cut -c 7-16 ncepdate`
export PDY=`cut -c 7-14 ncepdate`

##############################################
# Obtain unique process id (pid) and make temp directory
##############################################
export DATA=/gpfs/${delldir}/${tmpdir}/${LOGNAME}/tmpnwprd_hourly/${jobname}
mkdir -p $DATA
cd $DATA

export pid=$$
export pgmout="OUTPUT.${pid}"

##############################################
# Define COM directories
##############################################
#COMROOT and GESROOT are the same dirs
mkdir -p $COMROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}
export COMOUT=$COMROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}
export NWGES=$GESROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}

##############################################
# Execute the script.
##############################################
${SCRIPTdir}/exfv3sar_rhist.sh

if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $DATA ; fi

date

exit
