#!/bin/ksh -l
 set -x

. $HOMEfv3/jobs/JFV3CAM_SAR_ENVIR

module load grib_util/1.0.6

##############################################
# SENDCOM - COpy files to /com directory
##############################################
export SENDCOM=${SENDCOM:-YES}

##############################################
# Initialize PDY variables
##############################################
#  PDY and CDATE are passed in through Rocoto xml
#setpdy.sh
#. ./PDY

##############################################
# Obtain unique process id (pid) and make temp directory
##############################################
export INPUT_DATA=/gpfs/${delldir}/${tmpdir}/${USER}/tmpnwprd/forecast_firstguess_${cyc}
export DATA=/gpfs/${delldir}/${tmpdir}/${USER}/tmpnwprd/${job}_${cyc}
mkdir -p $DATA
cd $DATA

export pid=$$
export pgmout="OUTPUT.${pid}"

##############################################
# Specify Execution Areas
##############################################
export POSTGPEXEC=${EXECfv3}/ncep_post
export WGRIB2=${EXECfv3}/wgrib2new

##############################################
# Define COM directories
##############################################
export COMOUT=$COMROOT/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $COMOUT
export NWGES=$GESROOT/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $NWGES

##############################################
# Execute the script.
##############################################
${HOMEfv3}/scripts/exfv3cam_post_firstguess.sh

cat err 
cat $pgmout

if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $INPUT_DATA ; fi
if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $DATA ; fi

date

exit
