#!/bin/ksh
set -x

. $HOMEfv3/jobs/JFV3CAM_SAR_ENVIR

export DATA=${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}
cd $DATA

export pid=$$
export pgmout="OUTPUT.${pid}"

FTPdir=/home/ftp/emc/mmb/mmbpll/${RUN}/${RUN}.${PDY}/${cyc}
# The directory has already been created by the SENDINIBC job, don't need to create again
#ssh -l ${rzdmuser} emcrzdm.ncep.noaa.gov "mkdir -p $FTPdir" 

posthr=00
while [ $posthr -le 61 ] ; do
  scp ${RUN}.t${cyc}z.conusgoestb.f${posthr}.grib2 ${rzdmuser}@emcrzdm.ncep.noaa.gov:$FTPdir/.
  let "posthr=posthr+1"
  typeset -Z2 posthr
done


# delete 3-day old com on emcrzdm

#if [ $cyc -eq 00 ] ; then

#TM72=`$NDATE -72 $CDATE`
#PDYm72=`echo $TM72 | cut -c 1-8`
#FTPTM72=/home/ftp/emc/mmb/mmbpll/${RUN}/${RUN}.${PDYm72}
#ssh -l ${rzdmuser} emcrzdm.ncep.noaa.gov "rm -r ${FTPTM72}"

#fi

echo "I am done" > donefile.postgoestb.${CDATE}
scp donefile.post.${CDATE} ${rzdmuser}@emcrzdm.ncep.noaa.gov:$FTPdir/.

# if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $DATA ; fi

date

exit
