#!/bin/ksh
 
set -x

# HOMEdir set in qsub job

. $HOMEdir/jobs/JFV3SAR_ENVIR

. /usrx/local/prod/lmod/lmod/init/sh

module purge
module use ${HOMEgfs}/sorc/fv3gfs.fd/modulefiles/wcoss_dell_p3
module load fv3
module load prod_util/1.1.0
module list

##############################################
# Specify Execution Areas
##############################################
export EXECfv3=${HOMEgfs}/exec

# CONFIGdir, FIX_AM, FIXDIR set in JFV3SAR_ENVIR
export CO2DIR=${FIX_AM}/fix_co2_proj

##############################################
# Working directories
##############################################
mkdir -p /gpfs/${delldir}/${tmpdir}/${LOGNAME}/tmpnwprd_hourly/${jobname}_${cyc}
export DATA=/gpfs/${delldir}/${tmpdir}/${LOGNAME}/tmpnwprd_hourly/${jobname}_${cyc}
cd /gpfs/${delldir}/${tmpdir}/${LOGNAME}/tmpnwprd_hourly/${jobname}_${cyc}

##############################################
# Obtain unique process id (pid) and determine job output name on system
##############################################
export pid=$$
export pgmout="OUTPUT.${pid}"

##############################################
# Initialize PDY variables
##############################################
# Get my date file; cyc is tm00 date, comes from qsub script
cp $DATEdir/t${cyc}z ncepdate

###cp /com/date/t${cyc}z ncepdate
export CYCLE=`cut -c 7-16 ncepdate`
export PDY=`cut -c 7-14 ncepdate`

#get valid time of IC's
offset=`echo $tmmark | cut -c 3-4`
export CYCLEanl=`$NDATE -${offset} $CYCLE`

##############################################
# Define COM directories
##############################################
#COMROOT and GESROOT are the same dirs
mkdir -p $COMROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}
export COMOUT=$COMROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $GESROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}
export NWGES=$GESROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}

if [ $tmmark = tm06 ] ; then
  export tmmark_next=tm05
fi
if [ $tmmark = tm05 ] ; then
  export tmmark_next=tm04
fi
if [ $tmmark = tm04 ] ; then
  export tmmark_next=tm03
fi
if [ $tmmark = tm03 ] ; then
  export tmmark_next=tm02
fi
if [ $tmmark = tm02 ] ; then
  export tmmark_next=tm01
fi
if [ $tmmark = tm01 -o $tmmark = tm00 ] ; then
  export tmmark_next=tm00
fi

# get valid time of forecast 
offset_fcst=`echo $tmmark_next | cut -c 3-4`
export CYCLEfcst=`$NDATE -${offset_fcst} $CYCLE`
export PDYfcst=`echo $CYCLEfcst | cut -c 1-8`
export CYCfcst=`echo $CYCLEfcst | cut -c 9-10`

mkdir -p $COMOUT/guess.${tmmark_next}
mkdir -p $COMOUT/anl.${tmmark_next}
export GUESSdir=$COMOUT/guess.${tmmark_next}
export ANLdir=$COMOUT/anl.${tmmark_next}

##############################################
# Execute the script.
##############################################
${SCRIPTdir}/exfv3sar_fcst.sh

cat err 
cat $pgmout

if [ $tmmark != tm00 ] ; then
  if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $DATA ; fi
fi

date

exit
