#!/bin/ksh
 
set -x

# HOMEdir set in qsub job

. $HOMEdir/jobs/JFV3SAR_ENVIR

. /usrx/local/prod/lmod/lmod/init/ksh
module purge
module use ${HOMEgfs}/sorc/fv3gfs.fd/modulefiles/wcoss_dell_p3
module load fv3
module load prod_util/1.1.0
module list

##############################################
# Initialize PDY variables
##############################################
# CYCLE and PDY now come from rocoto script
echo "DATEXX${CYCLE}" > ncepdate

# fhr and cyc set in jobname in LSF script

##############################################
# Obtain unique process id (pid) and make temp directory
##############################################
export DATA=/gpfs/${delldir}/${tmpdir}/${LOGNAME}/tmpnwprd_hourly/${job}_${cyc}
mkdir -p $DATA
cd $DATA

export pid=$$
export pgmout="OUTPUT.${pid}"

##############################################
# Specify Execution Areas
##############################################
export EXECfv3=${HOMEgfs}/exec
export FCSTDIR=/gpfs/${delldir}/${tmpdir}/${LOGNAME}/tmpnwprd_hourly/forecast_firstguess_${cyc}

export WGRIB2=/gpfs/dell2/emc/modeling/noscrub/${USER}/fv3reg_da_hourly/exec/wgrib2new

##############################################
# Define COM directories
##############################################
#COMROOT and GESROOT are the same dirs
mkdir -p $COMROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}
export COMOUT=$COMROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $GESROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}
export NWGES=$GESROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}

##############################################
# Execute the script.
##############################################
${SCRIPTdir}/exfv3sar_post_firstguess.sh

cat err 
cat $pgmout

if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $FCSTDIR ; fi
if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $DATA ; fi

date

exit
