#!/bin/ksh
set -x

. $HOMEfv3/jobs/JNEST_ENVIR

####################################
# Run setpdy and initialize PDY variables
####################################
# PDY, CDATE, and tmmark are passed in through Rocoto xml
#setpdy.sh
#. ./PDY

#####################################
# Working directories
#####################################
export DATA=${DATA:-${mainroot}/${tmpdir}/${USER}/tmpnwprd_nest/${job}}
if [ -d $DATA ]; then
  rm -rf $DATA
fi
mkdir -p $DATA
cd $DATA

export pid=$$
export pgmout="OUTPUT.${pid}"

#####################################
# Define COM directories
#####################################
export COMOUT=${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $COMOUT
export NWGES=${GESROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $NWGES

export GUESSdir=$NWGES/guess.${tmmark}
mkdir -p $GUESSdir

#####################################
# wcoss environment settings
#####################################
export OMP_NUM_THREADS=2
export KMP_STACKSIZE=1024m

env

#####################################
# Execute the script.
${HOMEfv3}/scripts/exnest_forecast.sh
export err=$?
#####################################

cat err
cat $pgmout

exit $err
