#!/bin/ksh
set -x

. $HOMEfv3/jobs/JNEST_ENVIR

####################################
# Specify Execution Areas
####################################
export CHGRESEXEC=$EXECfv3/regional_chgres.x
export CHGRESSH=$USHfv3/regional_chgres.sh

####################################
# Run setpdy and initialize PDY variables
####################################
# PDY, CDATE, and tmmark are passed in through Rocoto xml
#setpdy.sh
#. ./PDY

#####################################
# Working directories
#####################################
export DATA=${DATA:-${STMP}/tmpnwprd_nest/${job}}
mkdir -p $DATA
cd $DATA

export OUTDIR=$DATA/INPUT
mkdir -p $OUTDIR

export pid=$$
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

#####################################
# Define COM directories
#####################################
export COMINgfs=${COMINgfs:-/gpfs/dell1/nco/ops/com/gfs/prod}
export INIDIR=${COMINgfs}/gfs.$PDY/$cyc

export COMOUT=${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $COMOUT
export NWGES=${GESROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $NWGES

export INPdir=$NWGES/guess.$tmmark
mkdir -p $INPdir

#####################################
# wcoss environment settings
#####################################
export CDUMP=gfs
export LEVS=65
export LSOIL=4
export REGIONAL=0		# REGIONAL=0 - uniform, stretch, or nest
				# REGIONAL=1 - generate data and boundary (for regional case)
				# REGIONAL=2 - generate boundaries only (for regional case)
export ictype=pfv3gfs
export nst_anl=.false.		# false or true to include NST analysis
export KMP_AFFINITY=disabled
export NTRAC=7			# output all gfdl mp tracers

env

#####################################
# Execute the script.
${HOMEfv3}/scripts/exnest_make_ic.sh
export err=$?
#####################################

if [ -e $pgmerr ] ; then
cat $pgmerr
fi

if [ -e $pgmout ] ; then
cat $pgmout
fi

exit $err
