#!/bin/bash
set -x

. $HOMEfv3/jobs/JNEST_ENVIR

####################################
# Run setpdy and initialize PDY variables
####################################
# PDY is passed in through Rocoto xml
#setpdy.sh
#. ./PDY

#####################################
# Working directories
#####################################
export PTMP=${PTMP:-""}
export STMP=${STMP:-""}

#####################################
# Execute the script.
${HOMEfv3}/scripts/exregional_cleanup.sh
export err=$?
#####################################

cat err
cat $pgmout

exit $err
