#!/bin/bash

#
#-----------------------------------------------------------------------
#
# This script generates both the initial conditions (ICs) and the lateral
# boundary conditions (LBCs) files for the air quality model (AQM) from
# files stored either in the system directory or on mass storage (HPSS).
#
#-----------------------------------------------------------------------
#

#
#-----------------------------------------------------------------------
#
# Source the variable definitions file and the bash utility functions.
#
#-----------------------------------------------------------------------
#
. ${GLOBAL_VAR_DEFNS_FP}
. $USHDIR/source_util_funcs.sh
#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
{ save_shell_opts; set -u +x; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#
#-----------------------------------------------------------------------
#
scrfunc_fp=$( $READLINK -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )
#
#-----------------------------------------------------------------------
#
# Print message indicating entry into script.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that copies/fetches to a local 
directory (either from disk or HPSS) the aqm boundary conditions from 
which the model needs.
========================================================================"
#
#-----------------------------------------------------------------------
#
# Create the directory EXTRN_MDL_FILES_DIR if it doesn't already exist.  
# This is the directory in which we will create a subdirectory for each 
# cycle (i.e. for each CDATE) in which to store the files from the 
# external model.
#
#-----------------------------------------------------------------------
#
EXTRN_MDL_FILES_DIR="${CYCLE_DIR}/AQM/tmp_AQLBCS"

mkdir_vrfy -p "${EXTRN_MDL_FILES_DIR}"
cd_vrfy ${EXTRN_MDL_FILES_DIR} || print_err_msg_exit "\
Could not change directory to EXTRN_MDL_FILES_DIR:
  EXTRN_MDL_FILES_DIR = \"${EXTRN_MDL_FILES_DIR}\""
#
#-----------------------------------------------------------------------
#
# Call the ex-script for this J-job and pass to it the necessary variables.
#
#-----------------------------------------------------------------------
#

$SCRIPTSDIR/exregional_add_aqm_lbcs.sh || \
print_err_msg_exit "\
Call to ex-script corresponding to J-job \"${scrfunc_fn}\" failed."
#
#-----------------------------------------------------------------------
#
# Print exit message.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/function.
#
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1

