#!/bin/ksh -l
set -xe

. $HOMEfv3/jobs/JREGIONAL_ENVIR
. $USHfv3/run_commands_bc.sh

####################################
# Specify Execution Areas
####################################
export CHGRESEXEC=$EXECfv3/regional_chgres_cube.x

####################################
# Run setpdy and initialize PDY variables
####################################
# PDY, CDATE, and tmmark are passed in through Rocoto xml
#setpdy.sh
#. ./PDY

export month=`echo $CDATE | cut -c 5-6`
export day=`echo $CDATE | cut -c 7-8`

offset=`echo $tmmark | cut -c 3-4`
export CYCLEGUESS=`$NDATE -${offset} $CDATE`
export CDATE=$CYCLEGUESS
export ymd=`echo $CDATE | cut -c 1-8`
export hhcyc=`echo $CDATE | cut -c 9-10`

#####################################
# Obtain unique process id (pid) and make temp directory
#####################################
export DATA=${DATA:-${STMP}/tmpnwprd/${job}}
mkdir -p $DATA
cd $DATA
export BNDYdir=$DATA

export pid=$$
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

#####################################
# Define COM directories
#####################################
export COMINgdas=${COMINgdas:-/gpfs/dell1/nco/ops/com/gfs/prod}
export GBCOMINgfs=${GBCOMINgfs:-/gpfs/dell1/nco/ops/com/gfs/prod}
export COMINgfs=${COMINgfs:-/gpfs/dell1/nco/ops/com/gfs/prod}
export INIDIR=${COMINgfs}/gfs.$PDY/$cyc

export COMOUT=${COMROOT}/${RUN}.${PDY}/${cyc}
mkdir -p $COMOUT
export NWGES=${GESROOT}/${RUN}.${PDY}/${cyc}
mkdir -p $NWGES

export INPdir=${NWGES}
mkdir -p ${INPdir}

#####################################
# wcoss environment settings
#####################################
if [ $tmmark = tm00 ] ; then
  export CDUMP=gfs
else
  export CDUMP=gdas
fi
export CDAS=gfs
export LEVS=65
export LSOIL=4
export REGIONAL=2		# REGIONAL=0 - uniform, stretch, or nest
				# REGIONAL=1 - generate data and boundary (for regional case)
				# REGIONAL=2 - generate boundaries only (for regional case)
export HALO=4
export ictype=pfv3gfs
export nst_anl=.false.		# false or true to include NST analysis
export KMP_AFFINITY=disabled

env

#####################################
# Generate the BCs
#####################################
# Execute the script
$HOMEfv3/scripts/exregional_make_bc.sh
export err=$?
#####################################

if [ -e $pgmerr ] ; then
cat $pgmerr
fi

if [ -e $pgmout ] ; then
cat $pgmout
fi

exit $err
