#!/bin/bash

#
#-----------------------------------------------------------------------
#
# Source the variable definitions file and the bash utility functions.
#
#-----------------------------------------------------------------------
#
. ${GLOBAL_VAR_DEFNS_FP}
. $USHDIR/source_util_funcs.sh
#
#-----------------------------------------------------------------------
#
# Source the file defining the function that will be used to set various
# external-model-related variables.
#
#-----------------------------------------------------------------------
#
. $USHDIR/get_extrn_mdl_file_dir_info.sh
#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
{ save_shell_opts; set -u +x; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#
#-----------------------------------------------------------------------
#
scrfunc_fp=$( readlink -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )
#
#-----------------------------------------------------------------------
#
# Print message indicating entry into script.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that generates lateral boundary 
condition (LBC) files (in NetCDF format) for all LBC update hours (ex-
cept hour zero). 
========================================================================"
#
#-----------------------------------------------------------------------
#
# Set the name of and create the directory in which the output from this
# script will be placed (if it doesn't already exist).
#
#-----------------------------------------------------------------------
#
LBCS_DIR="${CYCLE_DIR}/INPUT"
mkdir_vrfy -p "${LBCS_DIR}"
#
#-----------------------------------------------------------------------
#
# Retrieve platform's parallel application launcher command.
#
#-----------------------------------------------------------------------
#
get_platform_info \
    num_pes="48" \
    num_threads="2" \
    varname_run_cmd="APRUN" \
    varname_stack_size="stack_size"

ulimit -s ${stack_size} > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Call the function that sets various external-model-related variables.
# See the function defintion file for the definitions of these varia-
# bles.
#
#-----------------------------------------------------------------------
#
get_extrn_mdl_file_dir_info \
  extrn_mdl_name="${EXTRN_MDL_NAME_LBCS}" \
  anl_or_fcst="FCST" \
  cdate_FV3SAR="${CDATE}" \
  time_offset_hrs="${EXTRN_MDL_LBCS_OFFSET_HRS}" \
  varname_extrn_mdl_cdate="EXTRN_MDL_CDATE" \
  varname_extrn_mdl_lbc_update_fhrs="EXTRN_MDL_LBC_UPDATE_FHRS" \
  varname_extrn_mdl_fns="EXTRN_MDL_FNS" \
  varname_extrn_mdl_sysdir="EXTRN_MDL_SYSDIR" \
  varname_extrn_mdl_arcv_fmt="EXTRN_MDL_ARCV_FMT" \
  varname_extrn_mdl_arcv_fns="EXTRN_MDL_ARCV_FNS" \
  varname_extrn_mdl_arcv_fps="EXTRN_MDL_ARCV_FPS" \
  varname_extrn_mdl_arcvrel_dir="EXTRN_MDL_ARCVREL_DIR"
#
#-----------------------------------------------------------------------
#
# Find the directory in which the wgrib2 executable is located.
#
#-----------------------------------------------------------------------
#
WGRIB2_DIR=$( which wgrib2 ) || print_err_msg_exit "\
Directory in which the wgrib2 executable is located not found:
  WGRIB2_DIR = \"${WGRIB2_DIR}\""
#
#-----------------------------------------------------------------------
#
# Set the directory containing the external model output files.
#
#-----------------------------------------------------------------------
#
EXTRN_MDL_FILES_DIR="${CYCLE_DIR}/${EXTRN_MDL_NAME_LBCS}/LBCS"
#
#-----------------------------------------------------------------------
#
# Call the ex-script for this J-job and pass to it the necessary varia-
# bles.
#
#-----------------------------------------------------------------------
#
EXTRN_MDL_FNS_str="( "$( printf "\"%s\" " "${EXTRN_MDL_FNS[@]}" )")"
EXTRN_MDL_LBC_UPDATE_FHRS_str="( "$( printf "\"%s\" " "${EXTRN_MDL_LBC_UPDATE_FHRS[@]}" )")"

$SCRIPTSDIR/exregional_make_lbcs.sh \
  EXTRN_MDL_FNS="${EXTRN_MDL_FNS_str}" \
  EXTRN_MDL_FILES_DIR="${EXTRN_MDL_FILES_DIR}" \
  EXTRN_MDL_CDATE="${EXTRN_MDL_CDATE}" \
  WGRIB2_DIR="${WGRIB2_DIR}" \
  APRUN="${APRUN}" \
  LBCS_DIR="${LBCS_DIR}" \
  EXTRN_MDL_LBC_UPDATE_FHRS="${EXTRN_MDL_LBC_UPDATE_FHRS_str}" || \
print_err_msg_exit "\
Call to ex-script corresponding to J-job \"${scrfunc_fn}\" failed."
#
#-----------------------------------------------------------------------
#
# Print exit message.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/func-
# tion.
#
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1

