#!/bin/ksh
set -x

. $HOMEfv3/jobs/JREGIONAL_ENVIR

####################################
# Specify Execution Areas
####################################
export CHGRESEXEC=$EXECfv3/regional_chgres.x
export CHGRESSH=$USHfv3/regional_chgres.sh
export GETGES=$HOMEfv3/util/ush/getges_linkges_hourlypgrb_new.sh

####################################
# Run setpdy and initialize PDY variables
####################################
# PDY, CDATE, and tmmark are passed in through Rocoto xml
#setpdy.sh
#. ./PDY

export CYCLEguess=`$NDATE -12 $CDATE`
export ymd=`echo $CDATE | cut -c 1-8`
export hhcyc=`echo $CDATE | cut -c 9-10`
export PDYtm12=`echo $CYCLEguess | cut -c 1-8`
export cycguess=`echo $CYCLEguess | cut -c 9-10`

#####################################
# Working directories
#####################################
export DATA=${DATA:-${mainroot}/${tmpdir}/${USER}/tmpnwprd/${job}}
mkdir -p $DATA
cd $DATA

export OUTDIR=$DATA/INPUT
mkdir -p $OUTDIR

export pid=$$
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

#####################################
# Define COM directories
#####################################
export COMINgdas=${COMINgdas:-/gpfs/dell1/nco/ops/com/gfs/prod}
export GBCOMINgfs=${GBCOMINgfs:-/gpfs/dell1/nco/ops/com/gfs/prod}
export COMINgfs=${COMINgfs:-/gpfs/dell1/nco/ops/com/gfs/prod}
export COMgfs=${COMgfs:-/gpfs/dell1/nco/ops/com/gfs/prod}
export INIDIR=${COMgfs}/gfs.$PDY/$cyc
export INIDIRtm12=${COMgfs}/gfs.$PDYtm12/$cycguess

export COMOUT=${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $COMOUT
export NWGES=${GESROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $NWGES

if [ $tmmark = tm12 ] ; then	# SAR-DA
  export INPdir=$NWGES/gfsanl.$tmmark
elif [ $tmmark = tm00 ] ; then	# SAR without DA
  export INPdir=$NWGES/anl.${dom}.$tmmark
fi
mkdir -p $INPdir

#####################################
# wcoss environment settings
#####################################
export CDUMP=gfs
export CDAS=gfs
export LEVS=65
export LSOIL=4
export REGIONAL=1		# REGIONAL=0 - uniform, stretch, or nest
				# REGIONAL=1 - generate data and boundary (for regional case)
				# REGIONAL=2 - generate boundaries only (for regional case)
export HALO=4
export ictype=pfv3gfs
export nst_anl=.false.		# false or true to include NST analysis
export KMP_AFFINITY=disabled
export NTRAC=7			# output all gfdl mp tracers

env

#####################################
# Generate the ICs and BC hour 0
#####################################
#
# set the links to use the 4 halo grid and orog files
# these are necessary for creating the boundary data
#
ln -sf $FIXsar/${CASE}_grid.tile7.halo4.nc $FIXsar/${CASE}_grid.tile7.nc
ln -sf $FIXsar/${CASE}_oro_data.tile7.halo4.nc $FIXsar/${CASE}_oro_data.tile7.nc

#####################################
# Execute the script.
${HOMEfv3}/scripts/exregional_make_ic_bc.sh
export err=$?
#####################################

mv $OUTDIR/gfs*nc $INPdir/.
mv $OUTDIR/sfc*nc $INPdir/.

#####################################
# Generate BCs for NHRSguess for SAR-DA
#####################################
if [ $tmmark = tm12 ] ; then
  export REGIONAL=2

# NHRSguess comes from JREGIONAL_ENVIR
  hour=3
  end_hour=$NHRSguess
  while (test "$hour" -le "$end_hour")
  do
    if [ $hour -lt 10 ] ; then
      hour_name='00'$hour
    elif [ $hour -lt 100 ] ; then
      hour_name='0'$hour
    else
      hour_name=$hour
    fi

    export bchour=$hour_name
    ${HOMEfv3}/scripts/exregional_make_ic_bc.sh

    mv $OUTDIR/gfs_bndy.tile7.${bchour}.nc $INPdir/.

    err=$?
    if [ $err -ne 0 ] ; then
      echo "bndy file not created, abort"
      exit 10
    fi
    hour=`expr $hour + 3`
  done
fi

cat $pgmerr
cat $pgmout

exit $err
