#!/bin/ksh
 set -x

. $HOMEfv3/jobs/JREGIONAL_ENVIR
. $USHfv3/run_commands_forecast.sh

##############################################
# SENDCOM - COpy files to /com directory
##############################################
export SENDCOM=${SENDCOM:-YES}

##############################################
# Initialize PDY variables
##############################################
#  PDY and CDATE are passed in through Rocoto xml
#setpdy.sh
#. ./PDY

##############################################
# Obtain unique process id (pid) and make temp directory
##############################################
export INPUT_DATA=${STMP}/tmpnwprd/forecast_firstguess_${cyc}
export DATA=${STMP}/tmpnwprd/${job}
mkdir -p $DATA
cd $DATA

export pid=$$
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

##############################################
# Specify Execution Areas
##############################################
export POSTGPEXEC=${EXECfv3}/regional_post.x
export WGRIB2=${WGRIB2:-${EXECfv3}/wgrib2new}

##############################################
# Define COM directories
##############################################
export COMOUT=$COMROOT/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $COMOUT
export NWGES=$GESROOT/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $NWGES

##############################################
# Execute the script.
##############################################
${HOMEfv3}/scripts/exregional_post_firstguess.sh

if [ -e $pgmerr ] ; then
cat $pgmerr
fi

if [ -e $pgmout ] ; then
cat $pgmout
fi

if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $INPUT_DATA ; fi
if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $DATA ; fi

date

exit
