#!/bin/ksh
set -x

. $HOMEfv3/jobs/JREGIONAL_ENVIR

##################################
# Run setpdy and initialize PDY variables
##################################
# PDY is passed in through Rocoto xml
#setpdy.sh
#. ./PDY

##################################
# Working directories
##################################
export DATA=${DATA:-${STMP}/tmpnwprd/${job}}
mkdir -p $DATA
cd $DATA

export pid=$$
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

##################################
# Define COM directories
##################################
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}}
mkdir -p $COMOUT
export NWGES=${NWGES:-${GESROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}}

##################################
# Execute the script.
${HOMEfv3}/scripts/exregional_archive.sh
export err=$?
##################################

cat $pgmerr
cat $pgmout

if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $DATA ; fi

date

exit
