#!/bin/ksh
set -xe

. $HOMEfv3/jobs/JREGIONAL_ENVIR
. $USHfv3/run_commands_bc.sh

####################################
# Specify Execution Areas
####################################
export CHGRESEXEC=$EXECfv3/regional_chgres_cube.x

####################################
# Run setpdy and initialize PDY variables
####################################
# PDY, CDATE, and tmmark are passed in through Rocoto xml
#setpdy.sh
#. ./PDY

export month=`echo $CDATE | cut -c 5-6`
export day=`echo $CDATE | cut -c 7-8`

export CYCLEguess=`$NDATE -12 $CDATE`
export ymd=`echo $CDATE | cut -c 1-8`
export hhcyc=`echo $CDATE | cut -c 9-10`
export PDYtm12=`echo $CYCLEguess | cut -c 1-8`
export cycguess=`echo $CYCLEguess | cut -c 9-10`

#####################################
# Working directories
#####################################
export DATA=${DATA:-${STMP}/tmpnwprd/${job}}
mkdir -p $DATA
cd $DATA

export pid=$$
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

#####################################
# Define COM directories
#####################################
export COMINgdas=${COMINgdas:-/gpfs/dell1/nco/ops/com/gfs/prod}
export GBCOMINgfs=${GBCOMINgfs:-/gpfs/dell1/nco/ops/com/gfs/prod}
export COMINgfs=${COMINgfs:-/gpfs/dell1/nco/ops/com/gfs/prod}
export INIDIR=${COMINgfs}/gfs.$PDY/$cyc
export INIDIRtm12=${COMINgfs}/gfs.$PDYtm12/$cycguess

export COMOUT=${COMROOT}/${RUN}.${PDY}/${cyc}
mkdir -p $COMOUT
export NWGES=${GESROOT}/${RUN}.${PDY}/${cyc}
mkdir -p $NWGES

if [ $tmmark = tm12 ] ; then	# SAR-DA
  export INPdir=$NWGES/gfsanl.$tmmark
elif [ $tmmark = tm00 ] ; then	# SAR without DA
  export INPdir=$NWGES
fi
mkdir -p $INPdir

#####################################
# wcoss environment settings
#####################################
export CDUMP=gfs
export CDAS=gfs
export LEVS=65
export LSOIL=4
export REGIONAL=1		# REGIONAL=0 - uniform, stretch, or nest
				# REGIONAL=1 - generate data and boundary (for regional case)
				# REGIONAL=2 - generate boundaries only (for regional case)
export HALO=4
export ictype=pfv3gfs
export nst_anl=.false.		# false or true to include NST analysis
export KMP_AFFINITY=disabled

env

#####################################
# Generate the ICs and BC hour 0
#####################################
# Execute the script.
${HOMEfv3}/scripts/exregional_make_ic.sh
export err=$?
#####################################


#####################################
# Generate BCs for NHRSguess for SAR-DA
#####################################
if [ $tmmark = tm12 ] ; then
  export REGIONAL=2

# NHRSguess comes from JREGIONAL_ENVIR
  hour=3
  end_hour=$NHRSguess
  while (test "$hour" -le "$end_hour")
  do
    if [ $hour -lt 10 ] ; then
      hour_name='00'$hour
    elif [ $hour -lt 100 ] ; then
      hour_name='0'$hour
    else
      hour_name=$hour
    fi

    export bchour=$hour_name
    ${HOMEfv3}/scripts/exregional_make_ic.sh

    err=$?
    if [ $err -ne 0 ] ; then
      echo "bndy file not created, abort"
      exit 10
    fi
    hour=`expr $hour + 3`
  done
fi

if [ -e $pgmerr ] ; then
cat $pgmerr
fi

if [ -e $pgmout ] ; then
cat $pgmout
fi

exit $err
