MACHINE="hera"
ACCOUNT="fv3lam"
EXPT_SUBDIR="RRFS_baseline_winter"

VERBOSE="TRUE"

RUN_ENVIR="community"
PREEXISTING_DIR_METHOD="rename"

PREDEF_GRID_NAME="RRFS_NA_3km"
QUILTING="TRUE"

CCPP_PHYS_SUITE="FV3_RRFS_v1alpha"
FCST_LEN_HRS="36"
LBC_SPEC_INTVL_HRS="6"

DATE_FIRST_CYCL="20191125"
DATE_LAST_CYCL="20200109"
CYCL_HRS=( "00" )

EXTRN_MDL_NAME_ICS="FV3GFS"
EXTRN_MDL_NAME_LBCS="FV3GFS"

FV3GFS_FILE_FMT_ICS="nemsio"
FV3GFS_FILE_FMT_LBCS="grib2"

WTIME_RUN_FCST="08:00:00"

WTIME_GET_EXTRN_ICS="00:10:00"
WTIME_GET_EXTRN_LBCS="00:10:00"

MODEL="FV3_RRFS_v1alpha_3km_winter"
METPLUS_PATH="/contrib/METplus/METplus-4.0.0"
MET_INSTALL_DIR="/contrib/met/9.0.2"
CCPA_OBS_DIR="/scratch2/BMC/fv3lam/RRFS_baseline/obs_data/ccpa/proc"
MRMS_OBS_DIR="/scratch2/BMC/fv3lam/RRFS_baseline/obs_data/mrms/proc"
NDAS_OBS_DIR="/scratch2/BMC/fv3lam/RRFS_baseline/obs_data/ndas/proc"

RUN_TASK_MAKE_GRID="TRUE"
RUN_TASK_MAKE_OROG="TRUE"
RUN_TASK_MAKE_SFC_CLIMO="TRUE"
RUN_TASK_GET_OBS_CCPA="FALSE"
RUN_TASK_GET_OBS_MRMS="FALSE"
RUN_TASK_GET_OBS_NDAS="FALSE"
RUN_TASK_VX_GRIDSTAT="TRUE"
RUN_TASK_VX_POINTSTAT="TRUE"

DT_ATMOS="36"

NNODES_MAKE_ICS="12"
NNODES_MAKE_LBCS="12"
PPN_MAKE_ICS="4"
PPN_MAKE_LBCS="4"
WTIME_MAKE_LBCS="01:00:00"

PPN_RUN_FCST="24"

NNODES_RUN_POST="6"
PPN_RUN_POST="12"

OMP_STACKSIZE_RUN_FCST="2048m"

USE_USER_STAGED_EXTRN_FILES="TRUE"

EXTRN_MDL_SOURCE_BASEDIR_ICS="/scratch2/BMC/fv3lam/RRFS_baseline/model_data/FV3GFS"
EXTRN_MDL_FILES_ICS=( "gfs.atmanl.nemsio" "gfs.sfcanl.nemsio" )
EXTRN_MDL_SOURCE_BASEDIR_LBCS="/scratch2/BMC/fv3lam/RRFS_baseline/model_data/FV3GFS"
EXTRN_MDL_FILES_LBCS=( "gfs.pgrb2.0p25.f006" "gfs.pgrb2.0p25.f012" "gfs.pgrb2.0p25.f018" "gfs.pgrb2.0p25.f024" \
                       "gfs.pgrb2.0p25.f030" "gfs.pgrb2.0p25.f036" "gfs.pgrb2.0p25.f042" "gfs.pgrb2.0p25.f048" )
