MACHINE="hera"
ACCOUNT="gsd-fv3"
EXPT_BASEDIR="/scratch2/BMC/det/jwolff/HIWT/expt_dirs"
EXPT_SUBDIR="test_regional_workflow_add_metplus"

QUEUE_DEFAULT="batch"
QUEUE_HPSS="service"
QUEUE_FCST="batch"

VERBOSE="TRUE"

RUN_ENVIR="community"
PREEXISTING_DIR_METHOD="rename"

PREDEF_GRID_NAME="GSD_HRRR3km"
GRID_GEN_METHOD="JPgrid"
QUILTING="TRUE"
USE_CCPP="TRUE"
CCPP_PHYS_SUITE="FV3_GSD_SAR"
FCST_LEN_HRS="24"
LBC_SPEC_INTVL_HRS="3"

DATE_FIRST_CYCL="20191011"
DATE_LAST_CYCL="20191011"
CYCL_HRS=( "12" )

EXTRN_MDL_NAME_ICS="HRRRX"
EXTRN_MDL_NAME_LBCS="RAPX"

MODEL="FV3_GSD_SAR_GSD_HRRR3km"
METPLUS_PATH="/contrib/METplus/METplus-3.0"
MET_INSTALL_DIR="/contrib/met/9.0_anacondal"
CCPA_OBS_DIR="/scratch2/BMC/det/jwolff/HIWT/obs/ccpa/proc"
NDAS_OBS_DIR="/scratch2/BMC/det/jwolff/HIWT/obs/ndas/proc"

RUN_TASK_MAKE_GRID="TRUE"
RUN_TASK_MAKE_OROG="TRUE"
RUN_TASK_MAKE_SFC_CLIMO="TRUE"
RUN_TASK_VX_GRIDSTAT="TRUE"
RUN_TASK_VX_POINTSTAT="TRUE"

