MACHINE="hera"
ACCOUNT="fv3-cam"
EXPT_SUBDIR="test_cmaq"

VERBOSE="TRUE"
PRINT_ESMF="TRUE"

RUN_ENVIR="community"
PREEXISTING_DIR_METHOD="rename"

USE_CRON_TO_RELAUNCH="TRUE"
CRON_RELAUNCH_INTVL_MNTS="5"

PREDEF_GRID_NAME="GSD_HRRR_25km"
GRID_GEN_METHOD="ESGgrid"
HALO_BLEND="0"

QUILTING="TRUE"
CCPP_PHYS_SUITE="FV3_GFS_2017_gfdlmp"
FCST_LEN_HRS="12"
LBC_SPEC_INTVL_HRS="6"

DATE_FIRST_CYCL="20190804"
DATE_LAST_CYCL="20190804"
CYCL_HRS=( "12" )

EXTRN_MDL_NAME_ICS="FV3GFS"
EXTRN_MDL_NAME_LBCS="FV3GFS"

FV3GFS_FILE_FMT_ICS="nemsio"
FV3GFS_FILE_FMT_LBCS="nemsio"

WTIME_RUN_FCST="00:20:00"

RUN_TASK_ADD_AQM_LBCS="TRUE"
RUN_TASK_RUN_NEXUS="TRUE"

FV3_EXEC_FN="NEMS.x"
FV3_NML_BASE_SUITE_FN="input.nml.fv3gfs_aqm_FV3_GFS_2017_gfdlmp"
FV3_NML_YAML_CONFIG_FN="fv3gfs_aqm.input.yml"
#ENABLE_AQ="FALSE"

AQM_CONFIG_DIR="/scratch1/NCEPDEV/nems/Raffaele.Montuoro/dev/aqm/epa/data"
AQM_EMIS_DIR="/scratch1/NCEPDEV/nems/Raffaele.Montuoro/dev/fv3sar/data/bio"
AQM_FIRE_DIR="/scratch2/NCEPDEV/naqfc/Jianping.Huang/Data/emissions/GSCE/GBBEPx.in.C401/Reprocessed"
AQM_FIRE_FILE="GBBEPx_C401GRID.emissions_v003_20190804.nc"
AQM_LBCS_DIR="/scratch1/NCEPDEV/rstprod/nexus_emissions/LBCS"
AQM_LBCS_FILES="gfs_bndy_chem_<MM>.tile7.000.nc"
NEXUS_INPUT_DIR="/scratch1/NCEPDEV/rstprod/nexus_emissions"
