#!/usr/bin/env python3

import unittest

from python_utils.environment import import_vars, export_vars, set_env_var, get_env_var
from python_utils.print_msg import print_err_msg_exit

def set_extrn_mdl_params():
    """ Sets parameters associated with the external model used for initial 
    conditions (ICs) and lateral boundary conditions (LBCs).
    Args:
        None
    Returns:
        None
    """

    #import all env variables
    import_vars()

    global EXTRN_MDL_SYSBASEDIR_ICS, EXTRN_MDL_SYSBASEDIR_LBCS,  EXTRN_MDL_LBCS_OFFSET_HRS

    #
    #-----------------------------------------------------------------------
    #
    # Set the system directory (i.e. location on disk, not on HPSS) in which
    # the files generated by the external model specified by EXTRN_MDL_NAME_ICS 
    # that are necessary for generating initial condition (IC) and surface 
    # files for the FV3SAR are stored (usually for a limited time, e.g. for 
    # the GFS external model, 2 weeks on WCOSS and 2 days on hera).  If for 
    # a given cycle these files are available in this system directory, they 
    # will be copied over to a subdirectory under the cycle directory.  If 
    # these files are not available in the system directory, then we search 
    # for them elsewhere, e.g. in the mass store (HPSS).
    #
    #-----------------------------------------------------------------------
    #
    if RUN_ENVIR == "nco":
    
      EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or COMINgfs
    
    else:
    
      if EXTRN_MDL_NAME_ICS == "GSMGFS":
        if MACHINE  == "WCOSS_CRAY":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS
        elif MACHINE == "WCOSS_DELL_P3":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS
        elif MACHINE == "HERA":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS
        elif MACHINE == "ORION":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS
        elif MACHINE == "JET":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS
        elif MACHINE == "ODIN":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/scratch/ywang/EPIC/GDAS/2019053000_mem001"
        elif MACHINE == "CHEYENNE":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/glade/p/ral/jntp/UFS_CAM/COMGFS"
        elif MACHINE == "STAMPEDE":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/scratch/00315/tg455890/GDAS/20190530/2019053000_mem001"
    
      elif EXTRN_MDL_NAME_ICS == "FV3GFS":
        if MACHINE == "WCOSS_CRAY":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/gpfs/dell1/nco/ops/com/gfs/prod"
        elif MACHINE == "WCOSS_DELL_P3":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/gpfs/dell1/nco/ops/com/gfs/prod"
        elif MACHINE == "HERA":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/scratch1/NCEPDEV/rstprod/com/gfs/prod"
        elif MACHINE == "ORION":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS
        elif MACHINE == "JET":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/public/data/grids/gfs/nemsio"
        elif MACHINE == "ODIN":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/scratch/ywang/test_runs/FV3_regional/gfs"
        elif MACHINE == "STAMPEDE":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/scratch/00315/tg455890/GDAS/20190530/2019053000_mem001"
        elif MACHINE == "CHEYENNE":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/glade/p/ral/jntp/UFS_CAM/COMGFS"
    
      elif EXTRN_MDL_NAME_ICS == "RAP":
        if MACHINE == "WCOSS_CRAY":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/gpfs/hps/nco/ops/com/rap/prod"
        elif MACHINE == "WCOSS_DELL_P3":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/gpfs/hps/nco/ops/com/rap/prod"
        elif MACHINE == "HERA":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/scratch2/BMC/public/data/gsd/rap/full/wrfnat"
        elif MACHINE == "ORION":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS
        elif MACHINE == "JET":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/misc/whome/rtrr/rap"
        elif MACHINE == "CHEYENNE":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "dummy_value"
    
      elif EXTRN_MDL_NAME_ICS == "HRRR":
        if MACHINE == "WCOSS_CRAY":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/gpfs/hps/nco/ops/com/hrrr/prod"
        elif MACHINE == "WCOSS_DELL_P3":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/gpfs/hps/nco/ops/com/hrrr/prod"
        elif MACHINE == "HERA":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/scratch2/BMC/public/data/gsd/hrrr/conus/wrfnat"
        elif MACHINE == "ORION":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS
        elif MACHINE == "JET":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/misc/whome/rtrr/hrrr"
        elif MACHINE == "CHEYENNE":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "dummy_value"
    
      elif EXTRN_MDL_NAME_ICS == "NAM":
        if MACHINE == "WCOSS_CRAY":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/gpfs/dell1/nco/ops/com/nam/prod"
        elif MACHINE == "WCOSS_DELL_P3":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "/gpfs/dell1/nco/ops/com/nam/prod"
        elif MACHINE == "HERA":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "dummy_value"
        elif MACHINE == "CHEYENNE":
          EXTRN_MDL_SYSBASEDIR_ICS=EXTRN_MDL_SYSBASEDIR_ICS or "dummy_value"
    #
    # If EXTRN_MDL_SYSBASEDIR_ICS has not been set (not even to a null string), 
    # print out an error message and exit.
    #
    if not EXTRN_MDL_SYSBASEDIR_ICS:
      print_err_msg_exit(f'''
        The variable EXTRN_MDL_SYSBASEDIR_ICS specifying the system directory
        in which to look for the files generated by the external model for ICs
        has not been set for the current combination of machine (MACHINE) and 
        external model (EXTRN_MDL_NAME_ICS):
          MACHINE = \"{MACHINE}\"
          EXTRN_MDL_NAME_ICS = \"{EXTRN_MDL_NAME_ICS}\"''')
    #
    #-----------------------------------------------------------------------
    #
    # Set EXTRN_MDL_LBCS_OFFSET_HRS, which is the number of hours to shift 
    # the starting time of the external model that provides lateral boundary 
    # conditions.
    #
    #-----------------------------------------------------------------------
    #
    if EXTRN_MDL_NAME_LBCS == "GSMGFS":
        EXTRN_MDL_LBCS_OFFSET_HRS="0"
    elif EXTRN_MDL_NAME_LBCS == "FV3GFS":
        EXTRN_MDL_LBCS_OFFSET_HRS="0"
    elif EXTRN_MDL_NAME_LBCS == "RAP":
        EXTRN_MDL_LBCS_OFFSET_HRS="3"
    elif EXTRN_MDL_NAME_LBCS == "HRRR":
        EXTRN_MDL_LBCS_OFFSET_HRS="0"
    elif EXTRN_MDL_NAME_LBCS == "NAM":
        EXTRN_MDL_LBCS_OFFSET_HRS="0"
    #
    #-----------------------------------------------------------------------
    #
    # Set the system directory (i.e. location on disk, not on HPSS) in which
    # the files generated by the external model specified by EXTRN_MDL_NAME_LBCS 
    # that are necessary for generating lateral boundary condition (LBC) files 
    # for the FV3SAR are stored (usually for a limited time, e.g. for the GFS 
    # external model, 2 weeks on WCOSS and 2 days on hera).  If for a given 
    # cycle these files are available in this system directory, they will be 
    # copied over to a subdirectory under the cycle directory.  If these files 
    # are not available in the system directory, then we search for them 
    # elsewhere, e.g. in the mass store (HPSS).
    #
    #-----------------------------------------------------------------------
    #
    if RUN_ENVIR == "nco":
    
      EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or COMINgfs
    
    else:
    
      if EXTRN_MDL_NAME_LBCS == "GSMGFS":
        if MACHINE == "WCOSS_CRAY":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS
        elif MACHINE == "WCOSS_DELL_P3":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS
        elif MACHINE == "HERA":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS
        elif MACHINE == "ORION":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS
        elif MACHINE == "JET":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS
        elif MACHINE == "ODIN":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "/scratch/ywang/EPIC/GDAS/2019053000_mem001"
        elif MACHINE == "CHEYENNE":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "/glade/p/ral/jntp/UFS_CAM/COMGFS"
        elif MACHINE == "STAMPEDE":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "/scratch/00315/tg455890/GDAS/20190530/2019053000_mem001"
    
      elif EXTRN_MDL_NAME_LBCS == "FV3GFS":
        if MACHINE == "WCOSS_CRAY":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "/gpfs/dell1/nco/ops/com/gfs/prod"
        elif MACHINE == "WCOSS_DELL_P3":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "/gpfs/dell1/nco/ops/com/gfs/prod"
        elif MACHINE == "HERA":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "/scratch1/NCEPDEV/rstprod/com/gfs/prod"
        elif MACHINE == "ORION":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS
        elif MACHINE == "JET":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "/public/data/grids/gfs/nemsio"
        elif MACHINE == "ODIN":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "/scratch/ywang/test_runs/FV3_regional/gfs"
        elif MACHINE == "CHEYENNE":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "/glade/p/ral/jntp/UFS_CAM/COMGFS"
        elif MACHINE == "STAMPEDE":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "/scratch/00315/tg455890/GDAS/20190530/2019053000_mem001"
    
      elif EXTRN_MDL_NAME_LBCS == "RAP":
        if MACHINE == "WCOSS_CRAY":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "/gpfs/hps/nco/ops/com/rap/prod"
        elif MACHINE == "WCOSS_DELL_P3":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "/gpfs/hps/nco/ops/com/rap/prod"
        elif MACHINE == "HERA":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "/scratch2/BMC/public/data/gsd/rap/full/wrfnat"
        elif MACHINE == "ORION":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS
        elif MACHINE == "JET":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "/misc/whome/rtrr/rap"
        elif MACHINE == "CHEYENNE":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "dummy_value"
    
      elif EXTRN_MDL_NAME_LBCS == "HRRR":
        if MACHINE == "WCOSS_CRAY":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "/gpfs/hps/nco/ops/com/hrrr/prod"
        elif MACHINE == "WCOSS_DELL_P3":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "/gpfs/hps/nco/ops/com/hrrr/prod"
        elif MACHINE == "HERA":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "/scratch2/BMC/public/data/gsd/hrrr/conus/wrfnat"
        elif MACHINE == "ORION":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS
        elif MACHINE == "JET":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "/misc/whome/rtrr/hrrr"
        elif MACHINE == "CHEYENNE":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "dummy_value"
    
      elif EXTRN_MDL_NAME_LBCS == "NAM":
        if MACHINE == "HERA":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "dummy_value"
        elif MACHINE == "CHEYENNE":
          EXTRN_MDL_SYSBASEDIR_LBCS=EXTRN_MDL_SYSBASEDIR_LBCS or "dummy_value"
    #
    # If EXTRN_MDL_SYSBASEDIR_LBCS has not been set (not even to a null string), 
    # print out an error message and exit.
    #
    if not EXTRN_MDL_SYSBASEDIR_LBCS:
      print_err_msg_exit(f'''
        The variable EXTRN_MDL_SYSBASEDIR_LBCS specifying the system directory
        in which to look for the files generated by the external model for LBCs
        has not been set for the current combination of machine (MACHINE) and 
        external model (EXTRN_MDL_NAME_LBCS):
          MACHINE = \"{MACHINE}\"
          EXTRN_MDL_NAME_LBCS = \"{EXTRN_MDL_NAME_LBCS}\"''')

    # export values we set above
    env_vars = ["EXTRN_MDL_SYSBASEDIR_ICS", "EXTRN_MDL_SYSBASEDIR_LBCS", "EXTRN_MDL_LBCS_OFFSET_HRS"]
    export_vars(env_vars=env_vars)
#
#-----------------------------------------------------------------------
#
# Call the function defined above.
#
#-----------------------------------------------------------------------
#
if __name__ == "__main__":
    set_extrn_mdl_params()
   
class Testing(unittest.TestCase):
    def test_extrn_mdl_params(self):
        set_extrn_mdl_params()
        EXTRN_MDL_SYSBASEDIR_ICS = get_env_var("EXTRN_MDL_SYSBASEDIR_ICS")
        COMINgfs = get_env_var("COMINgfs")
        self.assertEqual(EXTRN_MDL_SYSBASEDIR_ICS,COMINgfs)

    def setUp(self):
        set_env_var("MACHINE","HERA")
        set_env_var("RUN_ENVIR","nco")
        set_env_var("EXTRN_MDL_NAME_ICS","FV3GFS")
        set_env_var("EXTRN_MDL_NAME_LBCS","FV3GFS")
        set_env_var("EXTRN_MDL_SYSBASEDIR_ICS",None)
        set_env_var("EXTRN_MDL_SYSBASEDIR_LBCS",None)
        set_env_var("COMINgfs","/base/path/of/directory/containing/gfs/input/files")
