name: Python unittests
on: [push, pull_request]
  push:
    paths:
      - ush/*retrieve_data.py
      - ush/templates/data_locations.yml
  pull_request:

jobs:
  python_functests:
    name: Python Functional Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test:
          - test_gdas_ics_from_aws
          - test_gefs_grib2_ics_from_aws
          - test_hrrr_ics_from_aws
          - test_hrrr_lbcs_from_aws
          - test_rap_ics_from_aws
          - test_rap_lbcs_from_aws

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip netcdf-bin
          sudo pip3 install pyyaml jinja2 f90nml
          sudo pip3 install numpy matplotlib basemap

      # Run python unittests
      - name: Run python unittests
        run: |
          cd ush
          python3 -m unittest -b test_retrieve_data.FunctionalTesting.${{test}}
